format = """
$directory\
$git_branch\
$git_status\
$git_commit\
$fossil_branch\
$pijul_channel\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$buf\
$c\
$conda\
$crystal\
$dart\
$elixir\
$elm\
$fennel\
$haxe\
$java\
$julia\
$kotlin\
$nim\
$ocaml\
$perl\
$php\
$rlang\
$scala\
$swift\
$zig\
$nix_shell\
$guix_shell\
$package\
$gradle\
$docker_context\
$aws\
$meson\
$jobs\
$cmd_duration\
$memory_usage\
$line_break\
$character"""

add_newline = true
palette = "tokyonight"

[hostname]
ssh_symbol = " "

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '
read_only = '󰌾'

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:red'
format = '([$all_status$ahead_behind]($style) )'

[git_commit]
tag_symbol = '  '

[fossil_branch]
symbol = " "

[pijul_channel]
symbol = " "

[hg_branch]
symbol = " "

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[haxe]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[nim]
symbol = "󰆥 "

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[rlang]
symbol = "󰟔 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[nix_shell]
symbol = " "

[guix_shell]
symbol = " "

[package]
symbol = '󰏗 '

[gradle]
symbol = " "

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[meson]
symbol = "󰔷 "

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
cyan = '#8fbcbb'
black = '#2E3440'
white = '#D8DEE9'

[palettes.onedark]
dark_blue = '#61afef'
blue = '#56b6c2'
teal = '#88C0d0'
red = '#e06c75'
orange = '#be5046'
green = '#98c379'
yellow = '#e5c07b'
purple = '#c678dd'
gray = '#828997'
cyan = '#7dcfff'
black = '#2c323c'
white = '#abb2bf'

[palettes.tokyonight]
dark_blue = '#61afef'
blue = '#89ddff'
teal = '#4fd6be'
red = '#f7768e'
orange = '#ff9e64'
green = '#c3e88d'
yellow = '#ffc777'
purple = '#bb9af7'
gray = '#565f89'
cyan = '#7dcfff'
black = '#15161e'
white = '#c0caf5'
