[tools]
"cargo:gen-license" = "latest"
"cargo:gitnr" = "latest"
bun = "latest"
difftastic = "latest"
fastfetch = "latest"
java = "temurin-25"
lazygit = "latest"
ruby = "latest"
rust = "stable"
tree-sitter = "latest"

[env]
GOPATH = "{{env.HOME}}/.go"
